### PR TITLE
fix: 修复插入新的摄像头异常崩溃问题

### PR DESCRIPTION
**Pull request by lzwind**
修复插入新的摄像头异常崩溃问题

Log: 修复插入新的摄像头异常崩溃问题

Bug: https://pms.uniontech.com/bug-view-155719.html

/review 
@myk1343 @feeengli

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
