### PR TITLE
fix: 玲珑环境下通过dbus打开看图/影院

### PR DESCRIPTION
**Pull request by feeengli**
玲珑环境下通过dbus打开看图/影院预览

Log: 玲珑环境下通过dbus打开看图/影院预览

Bug: https://pms.uniontech.com/bug-view-148325.html
     https://pms.uniontech.com/bug-view-158031.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by jeffshuai** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
