### PR TITLE
fix: modify the default video format for recording to webm

### PR DESCRIPTION
**Pull request by feeengli**
For some hardware, modify the default video format for recording to webm

Log: For some hardware, modify the default video format for recording to webm

Bug: https://pms.uniontech.com/bug-view-227831.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]

**Pull request merged**
