### PR TITLE
fix: 修复主题切换相关bug

### PR DESCRIPTION
**Pull request by feeengli**
修复主题切换相关bug

Log: 修复主题切换相关bug

Bug: https://pms.uniontech.com/bug-view-156737.html
     https://pms.uniontech.com/bug-view-187173.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
