### PR TITLE
fix: 双击预览图片会打开两个窗口

### PR DESCRIPTION
**Pull request by feeengli**
修复双击预览图会打开两个窗口问题

Log: 修复双击预览图会打开两个窗口问题

Bug: https://pms.uniontech.com/bug-view-161843.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
