### PR TITLE
fix: klv录制视频花屏

### PR DESCRIPTION
**Pull request by feeengli**
klv录制mp4视频，播放时出现花屏

Log: 修复klv录制mp4视频花屏

Bug: https://pms.uniontech.com/bug-view-154693.html

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
