### PR TITLE
fix:  修复拍摄视频出现闪退

### PR DESCRIPTION
**Pull request by jeffshuai**
因ffmpeg从4升级5后API变动

Log:  修复拍摄视频出现闪退

Bug: https://pms.uniontech.com/bug-view-251245.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]

**Pull request merged**
