### PR TITLE
fix: merge branch 'release/eagle' to 'master'

### PR DESCRIPTION
**Pull request by feeengli**
合并release/eagle上的修改到master;添加系统版本判断，兼容V20与V23

Log: merge branch 'release/eagle' to 'master'

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
