### PR TITLE
fix: 修复ffmpeg升级后安装依赖报错

### PR DESCRIPTION
**Pull request by jeffshuai**
修复ffmpeg升级76后安装依赖报错

Log:  修复ffmpeg升级后安装依赖报错

Bug: https://pms.uniontech.com/bug-view-250209.html

### CODE REVIEW

**Review by Zeno-sole — APPROVED** [review]

**Comment by myk1343** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by pengfeixx — APPROVED** [review]

**Pull request merged**
