### PR TITLE
fix: 锁屏后快速解锁，相机崩溃

### PR DESCRIPTION
**Pull request by feeengli**
修复锁屏后快速解锁，相机崩溃问题

Log: 修复锁屏后快速解锁，相机崩溃问题

Bug: https://pms.uniontech.com/bug-view-198939.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
